create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  name text not null,
  offer_url text not null,
  network_payout numeric(12,2) default 0,
  user_reward numeric(12,2) default 0,
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists public.conversions (
  id bigint generated by default as identity primary key,
  offer_id bigint references public.offers(id),
  click_id text,
  wallet_id text,
  payout numeric(12,2) default 0,
  reward numeric(12,2) default 0,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  wallet_id text not null,
  upi_id text,
  amount numeric(12,2) not null,
  status text default 'pending',
  created_at timestamptz default now()
);